[project]
name = "lt25-grpo-debate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "unsloth>=2025.6.12",
    "vllm>=0.9.1",
    "wandb>=0.21.0",
]
